spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.230.196:3306/db_crm?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: soft@web

  data:
    redis:
      host: 121.196.230.196
      port: 6379
      password: zhz  # 如果没有密码，可以不写或写成空字符串